name: Build Rootless deb

on:
  workflow_dispatch:

env:
  THEOS: ${{ github.workspace }}/theos

jobs:
  build:
    runs-on: macos-latest

    steps:

      # 拉取源码
      - name: Checkout source
        uses: actions/checkout@v5


      # 设置 Xcode
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable


      # 安装 Theos
      - name: Install Theos
        uses: actions/checkout@v5
        with:
          repository: theos/theos
          path: theos
          submodules: recursive


      # 安装编译依赖
      - name: Install tools
        run: |
          brew install make dpkg ldid


      # 检查工程结构
      - name: Check structure
        run: |
          pwd
          ls -la
          ls -la tweak


      # 编译 Rootless deb
      - name: Build deb
        run: |
          cd tweak
          make package FINALPACKAGE=1 ROOTLESS=1


      # 上传 deb
      - name: Upload deb
        uses: actions/upload-artifact@v5
        with:
          name: spoti-rootless-deb
          path: tweak/packages/*.deb
          if-no-files-found: error
