name: Build Rootless deb

on:
  workflow_dispatch:

env:
  THEOS: ${{ github.workspace }}/theos

jobs:
  build:
    runs-on: macos-latest

    steps:

      # 拉取你的源码
      - name: Checkout source
        uses: actions/checkout@v5


      # 设置 Xcode
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable


      # 下载 Theos
      - name: Install Theos
        uses: actions/checkout@v5
        with:
          repository: theos/theos
          path: theos
          submodules: recursive


      # 安装编译工具
      - name: Install build tools
        run: |
          brew install make dpkg ldid


      # 编译 Rootless deb
      - name: Build deb package
        run: |
          make clean
          make package FINALPACKAGE=1 ROOTLESS=1


      # 上传 deb 文件
      - name: Upload deb
        uses: actions/upload-artifact@v5
        with:
          name: rootless-deb
          path: packages/*.deb
          if-no-files-found: error
