name: Build Rootless deb

on:
  workflow_dispatch:

env:
  THEOS: ${{ github.workspace }}/theos

jobs:
  build:
    runs-on: macos-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v5


      - name: Check project
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -name Makefile


      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable


      - name: Install Theos
        uses: actions/checkout@v5
        with:
          repository: theos/theos
          path: theos
          submodules: recursive


      - name: Install tools
        run: |
          brew install make dpkg ldid
          
      - name: Check structure
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -name Makefile -o -name "*.xm" -o -name "control"
      - name: Build deb
        run: ｜
          make package FINALPACKAGE=1 ROOTLESS=1


      - name: Upload deb
        uses: actions/upload-artifact@v5
        with:
          name: spoti-rootless-deb
          path: packages/*.deb
          if-no-files-found: error
